/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.rigel.gradle.tink

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class RigeldevGradleTinkPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'rigeldev.gradle.tink.greeting'")
            }
        }

        project.tasks.register("createKeyset", CreateKeySetTask::class.java)
    }
}
