/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.rigel.gradle.tink

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import java.util.*
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'dev.rigel.gradle.tink' plugin.
 */
class RigeldevGradleTinkPluginFunctionalTest {

    val projectDir = File("build/functionalTest/" + UUID.randomUUID().toString())

    @Test fun `can run task`() {
        // Setup the test build
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('dev.rigel.gradle.tink')
            }
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.withPluginClasspath()
        runner.withArguments("createKeyset","--keysetFile","keyset.json")
        runner.withProjectDir(projectDir)
        val result = runner.build();

        println(result.output.lines()
                .map { outputLine -> "[test output] $outputLine" }
                .joinToString("\n"))

        // Verify the keyset file is generated
        assertTrue(File(projectDir, "keyset.json").exists())
    }

    @AfterTest fun cleanUp() {
//        projectDir.deleteRecursively()
    }
}
