/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.rigel.gradle.tink

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'dev.rigel.gradle.tink' plugin.
 */
class RigeldevGradleTinkPluginTest {

    @Test fun `plugin registers extension`() {
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("dev.rigel.gradle.tink")

        assertNotNull(project.extensions.getByName("tink"))
    }

    @Test fun `plugin registers tasks`() {

        val project = ProjectBuilder.builder().build()
        project.plugins.apply("dev.rigel.gradle.tink")

        // key tasks
        assertNotNull(project.tasks.findByName("createKeyset"))

        // file tasks
        assertNotNull(project.tasks.findByName("encryptFile"))
        assertNotNull(project.tasks.findByName("decryptFile"))

        // string tasks
        assertNotNull(project.tasks.findByName("encryptString"))
        assertNotNull(project.tasks.findByName("decryptString"))

        // property tasks
        assertNotNull(project.tasks.findByName("encryptProperty"))
        assertNotNull(project.tasks.findByName("decryptProperty"))
    }
}
