/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.rigel.gradle.tink

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'dev.rigel.gradle.tink' plugin.
 */
class RigeldevGradleTinkPluginTest {

    @Test fun `plugin registers createKeySet task`() {

        val project = ProjectBuilder.builder().build()
        project.plugins.apply("dev.rigel.gradle.tink")

        assertNotNull(project.tasks.findByName("createKeyset"))

    }
}
